### ISSUE TITLE
print my record not working

### ISSUE THREAD

**Issue by ekavaliM** [amida-tech/DRE#723]
will also need to hide empty notes fields

**Comment by oehokie** [comment]
```
TypeError: dataservice.getData is not a function
    at refresh (http://localhost:3000/scripts/controllers/print.js:37:25)
    at activate (http://localhost:3000/scripts/controllers/print.js:30:9)
    at new Print (http://localhost:3000/scripts/controllers/print.js:24:5)
    at invoke (http://localhost:3000/bower_components/angular/angular.js:4426:17)
    at Object.instantiate (http://localhost:3000/bower_components/angular/angular.js:4434:27)
    at http://localhost:3000/bower_components/angular/angular.js:8943:28
    at link (http://localhost:3000/bower_components/angular-route/angular-route.js:977:26)
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8587:9)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8096:11)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7497:13) <div ng-view="" class="ng-scope" data-ng-animate="1">
```

I'll get this, has to do with a dataservice change
